### ISSUE TITLE
问个问题 你怎么知道AGP "D:\\Project\\AndroidProject\\Temp\\app\\build\\intermediates\\javac\\debug\\classes 这个下回自动打包的apk中啊

### ISSUE THREAD

**Issue by luhaoaimama1** [lxy1191/Temp#1]

**Comment by luhaoaimama1** [comment]
看到你这个是为了博客做的 能给个地址么 我去学习下

**Comment by lxy1191** [comment]
这只是我测试时的本地路径，而且我并没有成功，需要依次导入的包太多，不建议用这种方法


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lxy1191/Temp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午4:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lxy1191/Temp] 问个问题 你怎么知道AGP "D:\\Project\\AndroidProject\\Temp\\app\\build\\intermediates\\javac\\debug\\classes 这个下回自动打包的apk中啊 (Issue #1)





 
Closed #1 as completed.
